### ISSUE TITLE
Lack of role for lease control

### ISSUE THREAD

**Issue by shibuiwilliam** [d-kuro/scheduled-pod-autoscaler#60]
I get this error from a pod in deployment.apps/scheduled-pod-autoscaler.

```
E0313 06:48:33.345026       1 leaderelection.go:321] error retrieving resource lock kube-system/09d94c38.d-kuro.github.io: leases.coordination.k8s.io "09d94c38.d-kuro.github.io" is forbidden: User "system:serviceaccount:kube-system:scheduled-pod-autoscaler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
```

It seems the role or clusterrole is missing access to lease resources.

**Comment by shibuiwilliam** [comment]
PR
https://github.com/d-kuro/scheduled-pod-autoscaler/pull/61

**Comment by d-kuro** [comment]
@shibuiwilliam
Thank you for finding this Issue!
I just have one question.

The pull request below adds access to the lease object to the ClusterRole, but I don't think this is necessary. (I'm sorry to point out after merging)

https://github.com/d-kuro/scheduled-pod-autoscaler/pull/61/files

I'm thinking of allowing only kube-system namespace to have a Role that allows access to the lease object, is that ok?

https://github.com/d-kuro/scheduled-pod-autoscaler/blob/99bb623c49953fb5aca73b95243fe27aa1ac1bc6/config/rbac/leader_election_role.yaml#L2-L18

https://github.com/d-kuro/scheduled-pod-autoscaler/blob/99bb623c49953fb5aca73b95243fe27aa1ac1bc6/config/rbac/leader_election_role_binding.yaml#L1-L12

**Comment by d-kuro** [comment]
Changed to use Role for manifests provided by default, instead of using ClusterRole
If you have any issues, please reopen the issue and let us know 🙏 

https://github.com/d-kuro/scheduled-pod-autoscaler/blob/bb2199745ee571708ef11933eb4f32169d5fe090/manifests/rbac/leader_election_role.yaml
https://github.com/d-kuro/scheduled-pod-autoscaler/blob/bb2199745ee571708ef11933eb4f32169d5fe090/manifests/rbac/leader_election_role_binding.yaml
